### PR TITLE
Fixes and tests clean up

### LINKED ISSUE #12: Ability to pass username and password instead of token
Currently, we need to pass the token to the driver for authentication and authorization purposes. We should be able to pass a username and password instead of the token and the driver must be able to generate a token, refresh it when required and use that for any subsequent command executions.

### PR DESCRIPTION
**Pull request by kathirsvn**
**What this PR does**:

**Which issue(s) this PR fixes**:
Fixes to accept username and password instead of token, so the driver ll automatically generate/refresh token.
Fixes and test cases clean up based on integration testing JSON API server on local.

**Checklist**
- [X] Changes manually tested
- [ ] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CLA Signed: [DataStax CLA](https://cla.datastax.com/)

### CODE REVIEW

File: src/client/httpClient.ts [hunk 1]
```diff
@@ -114,12 +128,16 @@ export class HTTPClient {
...
-      //TODOV3 Replace this with auth call to get logged in user by providing username and password
-      throw new Error('applicationToken required for initialization');
-    } else{
+    this.username = options.username || '';
+    this.password = options.password || '';
+    this.authUrl = options.authUrl || this.baseUrl + AUTH_API_PATH;
+    if (options.applicationToken) {
       this.applicationToken = options.applicationToken;
+    }else{      
+      if(this.username === '' || this.password === ''){
```
Comment (vkarpov15) [inline src/client/httpClient.ts:137]: Should also throw this error if `!this.authUrl`. If authUrl is not set, you'll end up getting a `Invalid value 'undefined' for header "X-Cassandra-Token"` error whenever you run your first operation.

**Review by vkarpov15 — CHANGES_REQUESTED** [review]
I made a quick fix for a TypeScript build error, and pointed out a minor edge case I ran into. But otherwise, works great :+1: I tried it out with sample apps and it works.

File: src/client/httpClient.ts (hunk 1 above)
Comment (kathirsvn) [reply src/client/httpClient.ts:137]: I have a check before this condition as below to make sure the `authUrl` is always set. I believe that should take care?

`this.authUrl = options.authUrl || this.baseUrl + AUTH_API_PATH;`

Comment (kathirsvn) [reply src/client/httpClient.ts:137]: Hi @vkarpov15 could you please approve if this looks good?

Comment (vkarpov15) [reply src/client/httpClient.ts:137]: I took a look and my issue is due to the `authUrl` being incorrect. It looks like the `authUrl` should be `127.0.0.1:8081/v1/auth`. But the default `this.baseUrl + AUTH_API_PATH` becomes `127.0.0.1:8180/v1/auth`, different port.

Is the default value of `127.0.0.1:8180/v1/auth` expected to successfully return an auth token?

Also, would be nice to improve the error message if there's no access token. Right now, if auth fails, the error message is `Invalid value "undefined" for header "X-Cassandra-Token"`, which would be nice to improve.

Comment (kathirsvn) [reply src/client/httpClient.ts:137]: I set `this.baseUrl + AUTH_API_PATH` as the default because, while connecting to the AstraDB we don't have to change the `baseUrl`, just appending `AUTH_API_PATH` should take care of it.
But, on local or running against open source json api with separate auth endpoint, we will have to provide the `authUrl` separately as a connection option.

Comment (kathirsvn) [reply src/client/httpClient.ts:137]: Also, improved the error handling when no token is present. Please see commit [44f4024](https://github.com/stargate/stargate-mongoose/pull/25/commits/44f40247ed30d9cc6ff94455c94bf9d54c902143).

Please approve if this looks good.

**Review by vkarpov15 — APPROVED** [review]
LGTM :+1:

**Comment by kathirsvn** [comment]
Thanks @vkarpov15!
